// automatically generated by the FlatBuffers compiler, do not modify

package flatmath

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 4x3 matrix of ushorts
type Matrix4x3_u16 struct {
	_tab flatbuffers.Struct
}

func (rcv *Matrix4x3_u16) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Matrix4x3_u16) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Matrix4x3_u16) _0(obj *Vector3_u16) *Vector3_u16 {
	if obj == nil {
		obj = new(Vector3_u16)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+0)
	return obj
}
func (rcv *Matrix4x3_u16) _1(obj *Vector3_u16) *Vector3_u16 {
	if obj == nil {
		obj = new(Vector3_u16)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+6)
	return obj
}
func (rcv *Matrix4x3_u16) _2(obj *Vector3_u16) *Vector3_u16 {
	if obj == nil {
		obj = new(Vector3_u16)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+12)
	return obj
}
func (rcv *Matrix4x3_u16) _3(obj *Vector3_u16) *Vector3_u16 {
	if obj == nil {
		obj = new(Vector3_u16)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+18)
	return obj
}

func CreateMatrix4x3_u16(builder *flatbuffers.Builder, _0_x uint16, _0_y uint16, _0_z uint16, _1_x uint16, _1_y uint16, _1_z uint16, _2_x uint16, _2_y uint16, _2_z uint16, _3_x uint16, _3_y uint16, _3_z uint16) flatbuffers.UOffsetT {
	builder.Prep(2, 24)
	builder.Prep(2, 6)
	builder.PrependUint16(_3_z)
	builder.PrependUint16(_3_y)
	builder.PrependUint16(_3_x)
	builder.Prep(2, 6)
	builder.PrependUint16(_2_z)
	builder.PrependUint16(_2_y)
	builder.PrependUint16(_2_x)
	builder.Prep(2, 6)
	builder.PrependUint16(_1_z)
	builder.PrependUint16(_1_y)
	builder.PrependUint16(_1_x)
	builder.Prep(2, 6)
	builder.PrependUint16(_0_z)
	builder.PrependUint16(_0_y)
	builder.PrependUint16(_0_x)
	return builder.Offset()
}
