// automatically generated by the FlatBuffers compiler, do not modify

package flatmath

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 4x3 matrix of ints
type Matrix4x3_i32 struct {
	_tab flatbuffers.Struct
}

func (rcv *Matrix4x3_i32) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Matrix4x3_i32) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Matrix4x3_i32) _0(obj *Vector3_i32) *Vector3_i32 {
	if obj == nil {
		obj = new(Vector3_i32)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+0)
	return obj
}
func (rcv *Matrix4x3_i32) _1(obj *Vector3_i32) *Vector3_i32 {
	if obj == nil {
		obj = new(Vector3_i32)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+12)
	return obj
}
func (rcv *Matrix4x3_i32) _2(obj *Vector3_i32) *Vector3_i32 {
	if obj == nil {
		obj = new(Vector3_i32)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+24)
	return obj
}
func (rcv *Matrix4x3_i32) _3(obj *Vector3_i32) *Vector3_i32 {
	if obj == nil {
		obj = new(Vector3_i32)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+36)
	return obj
}

func CreateMatrix4x3_i32(builder *flatbuffers.Builder, _0_x int32, _0_y int32, _0_z int32, _1_x int32, _1_y int32, _1_z int32, _2_x int32, _2_y int32, _2_z int32, _3_x int32, _3_y int32, _3_z int32) flatbuffers.UOffsetT {
	builder.Prep(4, 48)
	builder.Prep(4, 12)
	builder.PrependInt32(_3_z)
	builder.PrependInt32(_3_y)
	builder.PrependInt32(_3_x)
	builder.Prep(4, 12)
	builder.PrependInt32(_2_z)
	builder.PrependInt32(_2_y)
	builder.PrependInt32(_2_x)
	builder.Prep(4, 12)
	builder.PrependInt32(_1_z)
	builder.PrependInt32(_1_y)
	builder.PrependInt32(_1_x)
	builder.Prep(4, 12)
	builder.PrependInt32(_0_z)
	builder.PrependInt32(_0_y)
	builder.PrependInt32(_0_x)
	return builder.Offset()
}
