// automatically generated by the FlatBuffers compiler, do not modify

package flatmath

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 3D vector of ints
type Vector3_i32 struct {
	_tab flatbuffers.Struct
}

func (rcv *Vector3_i32) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Vector3_i32) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Vector3_i32) X() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Vector3_i32) MutateX(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Vector3_i32) Y() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *Vector3_i32) MutateY(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *Vector3_i32) Z() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *Vector3_i32) MutateZ(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateVector3_i32(builder *flatbuffers.Builder, x int32, y int32, z int32) flatbuffers.UOffsetT {
	builder.Prep(4, 12)
	builder.PrependInt32(z)
	builder.PrependInt32(y)
	builder.PrependInt32(x)
	return builder.Offset()
}
