// automatically generated by the FlatBuffers compiler, do not modify

package flatmath

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

///-----------------------------------------------------------------------------
///-----------------------------------------------------------------------------
/// int types
/// 2D vector of ints
type Vector2_i32 struct {
	_tab flatbuffers.Struct
}

func (rcv *Vector2_i32) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Vector2_i32) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Vector2_i32) X() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Vector2_i32) MutateX(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Vector2_i32) Y() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *Vector2_i32) MutateY(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateVector2_i32(builder *flatbuffers.Builder, x int32, y int32) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.PrependInt32(y)
	builder.PrependInt32(x)
	return builder.Offset()
}
