// automatically generated by the FlatBuffers compiler, do not modify

package flatmath

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 2x4 matrix of shorts
type Matrix2x4_i16 struct {
	_tab flatbuffers.Struct
}

func (rcv *Matrix2x4_i16) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Matrix2x4_i16) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Matrix2x4_i16) _0(obj *Vector4_i16) *Vector4_i16 {
	if obj == nil {
		obj = new(Vector4_i16)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+0)
	return obj
}
func (rcv *Matrix2x4_i16) _1(obj *Vector4_i16) *Vector4_i16 {
	if obj == nil {
		obj = new(Vector4_i16)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+8)
	return obj
}

func CreateMatrix2x4_i16(builder *flatbuffers.Builder, _0_x int16, _0_y int16, _0_z int16, _0_w int16, _1_x int16, _1_y int16, _1_z int16, _1_w int16) flatbuffers.UOffsetT {
	builder.Prep(2, 16)
	builder.Prep(2, 8)
	builder.PrependInt16(_1_w)
	builder.PrependInt16(_1_z)
	builder.PrependInt16(_1_y)
	builder.PrependInt16(_1_x)
	builder.Prep(2, 8)
	builder.PrependInt16(_0_w)
	builder.PrependInt16(_0_z)
	builder.PrependInt16(_0_y)
	builder.PrependInt16(_0_x)
	return builder.Offset()
}
