// automatically generated by the FlatBuffers compiler, do not modify

package flatmath

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// RGB color of byte components
type ColorRGB_i8 struct {
	_tab flatbuffers.Struct
}

func (rcv *ColorRGB_i8) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ColorRGB_i8) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *ColorRGB_i8) R() int8 {
	return rcv._tab.GetInt8(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *ColorRGB_i8) MutateR(n int8) bool {
	return rcv._tab.MutateInt8(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *ColorRGB_i8) G() int8 {
	return rcv._tab.GetInt8(rcv._tab.Pos + flatbuffers.UOffsetT(1))
}
func (rcv *ColorRGB_i8) MutateG(n int8) bool {
	return rcv._tab.MutateInt8(rcv._tab.Pos+flatbuffers.UOffsetT(1), n)
}

func (rcv *ColorRGB_i8) B() int8 {
	return rcv._tab.GetInt8(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *ColorRGB_i8) MutateB(n int8) bool {
	return rcv._tab.MutateInt8(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func CreateColorRGB_i8(builder *flatbuffers.Builder, r int8, g int8, b int8) flatbuffers.UOffsetT {
	builder.Prep(1, 3)
	builder.PrependInt8(b)
	builder.PrependInt8(g)
	builder.PrependInt8(r)
	return builder.Offset()
}
