// automatically generated by the FlatBuffers compiler, do not modify

package flatmath

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 2x3 matrix of doubles
type Matrix2x3_f64 struct {
	_tab flatbuffers.Struct
}

func (rcv *Matrix2x3_f64) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Matrix2x3_f64) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Matrix2x3_f64) _0(obj *Vector3_f64) *Vector3_f64 {
	if obj == nil {
		obj = new(Vector3_f64)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+0)
	return obj
}
func (rcv *Matrix2x3_f64) _1(obj *Vector3_f64) *Vector3_f64 {
	if obj == nil {
		obj = new(Vector3_f64)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+24)
	return obj
}

func CreateMatrix2x3_f64(builder *flatbuffers.Builder, _0_x float64, _0_y float64, _0_z float64, _1_x float64, _1_y float64, _1_z float64) flatbuffers.UOffsetT {
	builder.Prep(8, 48)
	builder.Prep(8, 24)
	builder.PrependFloat64(_1_z)
	builder.PrependFloat64(_1_y)
	builder.PrependFloat64(_1_x)
	builder.Prep(8, 24)
	builder.PrependFloat64(_0_z)
	builder.PrependFloat64(_0_y)
	builder.PrependFloat64(_0_x)
	return builder.Offset()
}
