// automatically generated by the FlatBuffers compiler, do not modify

package flatmath

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 2x4 matrix of ints
type Matrix2x4_i32 struct {
	_tab flatbuffers.Struct
}

func (rcv *Matrix2x4_i32) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Matrix2x4_i32) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Matrix2x4_i32) _0(obj *Vector4_i32) *Vector4_i32 {
	if obj == nil {
		obj = new(Vector4_i32)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+0)
	return obj
}
func (rcv *Matrix2x4_i32) _1(obj *Vector4_i32) *Vector4_i32 {
	if obj == nil {
		obj = new(Vector4_i32)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+16)
	return obj
}

func CreateMatrix2x4_i32(builder *flatbuffers.Builder, _0_x int32, _0_y int32, _0_z int32, _0_w int32, _1_x int32, _1_y int32, _1_z int32, _1_w int32) flatbuffers.UOffsetT {
	builder.Prep(4, 32)
	builder.Prep(4, 16)
	builder.PrependInt32(_1_w)
	builder.PrependInt32(_1_z)
	builder.PrependInt32(_1_y)
	builder.PrependInt32(_1_x)
	builder.Prep(4, 16)
	builder.PrependInt32(_0_w)
	builder.PrependInt32(_0_z)
	builder.PrependInt32(_0_y)
	builder.PrependInt32(_0_x)
	return builder.Offset()
}
