// automatically generated by the FlatBuffers compiler, do not modify

package flatmath

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 4x4 matrix of uints
type Matrix4x4_u32 struct {
	_tab flatbuffers.Struct
}

func (rcv *Matrix4x4_u32) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Matrix4x4_u32) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Matrix4x4_u32) _0(obj *Vector4_u32) *Vector4_u32 {
	if obj == nil {
		obj = new(Vector4_u32)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+0)
	return obj
}
func (rcv *Matrix4x4_u32) _1(obj *Vector4_u32) *Vector4_u32 {
	if obj == nil {
		obj = new(Vector4_u32)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+16)
	return obj
}
func (rcv *Matrix4x4_u32) _2(obj *Vector4_u32) *Vector4_u32 {
	if obj == nil {
		obj = new(Vector4_u32)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+32)
	return obj
}
func (rcv *Matrix4x4_u32) _3(obj *Vector4_u32) *Vector4_u32 {
	if obj == nil {
		obj = new(Vector4_u32)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+48)
	return obj
}

func CreateMatrix4x4_u32(builder *flatbuffers.Builder, _0_x uint32, _0_y uint32, _0_z uint32, _0_w uint32, _1_x uint32, _1_y uint32, _1_z uint32, _1_w uint32, _2_x uint32, _2_y uint32, _2_z uint32, _2_w uint32, _3_x uint32, _3_y uint32, _3_z uint32, _3_w uint32) flatbuffers.UOffsetT {
	builder.Prep(4, 64)
	builder.Prep(4, 16)
	builder.PrependUint32(_3_w)
	builder.PrependUint32(_3_z)
	builder.PrependUint32(_3_y)
	builder.PrependUint32(_3_x)
	builder.Prep(4, 16)
	builder.PrependUint32(_2_w)
	builder.PrependUint32(_2_z)
	builder.PrependUint32(_2_y)
	builder.PrependUint32(_2_x)
	builder.Prep(4, 16)
	builder.PrependUint32(_1_w)
	builder.PrependUint32(_1_z)
	builder.PrependUint32(_1_y)
	builder.PrependUint32(_1_x)
	builder.Prep(4, 16)
	builder.PrependUint32(_0_w)
	builder.PrependUint32(_0_z)
	builder.PrependUint32(_0_y)
	builder.PrependUint32(_0_x)
	return builder.Offset()
}
