// automatically generated by the FlatBuffers compiler, do not modify

package flatmath

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 4D hypercomplex of shorts
type Quaternion_i16 struct {
	_tab flatbuffers.Struct
}

func (rcv *Quaternion_i16) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Quaternion_i16) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Quaternion_i16) X() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Quaternion_i16) MutateX(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Quaternion_i16) Y() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *Quaternion_i16) MutateY(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func (rcv *Quaternion_i16) Z() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *Quaternion_i16) MutateZ(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *Quaternion_i16) W() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(6))
}
func (rcv *Quaternion_i16) MutateW(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(6), n)
}

func CreateQuaternion_i16(builder *flatbuffers.Builder, x int16, y int16, z int16, w int16) flatbuffers.UOffsetT {
	builder.Prep(2, 8)
	builder.PrependInt16(w)
	builder.PrependInt16(z)
	builder.PrependInt16(y)
	builder.PrependInt16(x)
	return builder.Offset()
}
