// automatically generated by the FlatBuffers compiler, do not modify

package flatmath

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 4D vector of doubles (homogenous coordinates)
type Vector4_f64 struct {
	_tab flatbuffers.Struct
}

func (rcv *Vector4_f64) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Vector4_f64) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Vector4_f64) X() float64 {
	return rcv._tab.GetFloat64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Vector4_f64) MutateX(n float64) bool {
	return rcv._tab.MutateFloat64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Vector4_f64) Y() float64 {
	return rcv._tab.GetFloat64(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *Vector4_f64) MutateY(n float64) bool {
	return rcv._tab.MutateFloat64(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *Vector4_f64) Z() float64 {
	return rcv._tab.GetFloat64(rcv._tab.Pos + flatbuffers.UOffsetT(16))
}
func (rcv *Vector4_f64) MutateZ(n float64) bool {
	return rcv._tab.MutateFloat64(rcv._tab.Pos+flatbuffers.UOffsetT(16), n)
}

func (rcv *Vector4_f64) W() float64 {
	return rcv._tab.GetFloat64(rcv._tab.Pos + flatbuffers.UOffsetT(24))
}
func (rcv *Vector4_f64) MutateW(n float64) bool {
	return rcv._tab.MutateFloat64(rcv._tab.Pos+flatbuffers.UOffsetT(24), n)
}

func CreateVector4_f64(builder *flatbuffers.Builder, x float64, y float64, z float64, w float64) flatbuffers.UOffsetT {
	builder.Prep(8, 32)
	builder.PrependFloat64(w)
	builder.PrependFloat64(z)
	builder.PrependFloat64(y)
	builder.PrependFloat64(x)
	return builder.Offset()
}
